#include "perf_config.h"
#include "stm32f7xx_ll_pwr.h"
#include "stm32f7xx_ll_rcc.h"
#include "stm32f7xx_ll_bus.h"
#include "stm32f7xx_ll_utils.h"
#include "stm32f7xx_ll_system.h"

/* Private Prototype ******************************************************************/
/* Private Variable *******************************************************************/
static uint8_t StandbyState = 0;

const PLLParamCon_TypeDef ClockRateScale_Low[] = { 
  {LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_15, 144, LL_RCC_PLLP_DIV_4,LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
  {LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 244, LL_RCC_PLLP_DIV_4, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
  {LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 248, LL_RCC_PLLP_DIV_4, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
  {LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 252, LL_RCC_PLLP_DIV_4, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
  {LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 256, LL_RCC_PLLP_DIV_4, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
  {LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_15, 156, LL_RCC_PLLP_DIV_4, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
  {LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 264, LL_RCC_PLLP_DIV_4, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
  {LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 134, LL_RCC_PLLP_DIV_4, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
  {LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 272, LL_RCC_PLLP_DIV_4, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
  {LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 276, LL_RCC_PLLP_DIV_4, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_15, 168, LL_RCC_PLLP_DIV_4, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 284, LL_RCC_PLLP_DIV_4, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 288, LL_RCC_PLLP_DIV_4, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 292, LL_RCC_PLLP_DIV_4, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 296, LL_RCC_PLLP_DIV_4, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_12, 144, LL_RCC_PLLP_DIV_4, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 304, LL_RCC_PLLP_DIV_4, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 308, LL_RCC_PLLP_DIV_4, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 312, LL_RCC_PLLP_DIV_4, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 316, LL_RCC_PLLP_DIV_4, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_15, 192, LL_RCC_PLLP_DIV_4, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 324, LL_RCC_PLLP_DIV_4, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 328, LL_RCC_PLLP_DIV_4, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 332, LL_RCC_PLLP_DIV_4, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 336, LL_RCC_PLLP_DIV_4, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_15, 204, LL_RCC_PLLP_DIV_4, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 344, LL_RCC_PLLP_DIV_4, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 348, LL_RCC_PLLP_DIV_4, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 352, LL_RCC_PLLP_DIV_4, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 356, LL_RCC_PLLP_DIV_4, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_15, 216, LL_RCC_PLLP_DIV_4, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 364, LL_RCC_PLLP_DIV_4, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 368, LL_RCC_PLLP_DIV_4, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 372, LL_RCC_PLLP_DIV_4, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 376, LL_RCC_PLLP_DIV_4, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_15, 228, LL_RCC_PLLP_DIV_4, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 192, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 194, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 196, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 198, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_12, 96, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 202, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 204, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 206, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 208, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_15, 126, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 212, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 214, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 216, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 109, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 110, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 111, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 112, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 113, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 114, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 115, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 116, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 234, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 236, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 238, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_15, 144, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 242, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 244, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 246, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 248, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_12, 120, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 252, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 254, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 256, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 258, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_15, 156, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 262, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 264, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 266, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 134, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_15, 162, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 272, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 274, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 276, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 278, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_15, 168, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 282, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 284, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 286, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 288, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2}
};
const PLLParamCon_TypeDef ClockRateScale_High[] = { 
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_15, 216, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 362, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 364, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 366, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 368, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_15, 222, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 372, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 374, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 376, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 378, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_15, 228, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 382, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 384, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 386, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 388, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_15, 234, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 392, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 394, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 396, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 398, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_12, 192, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 201, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 404, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 203, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 408, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 205, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 412, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 207, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 416, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 418, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_15, 252, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 422, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 424, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 426, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 428, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_15, 258, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2},
{LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 432, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2}
};
const PLLParamCon_TypeDef ClockRateScale_Medium = {LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_25, 336, LL_RCC_PLLP_DIV_2, LL_RCC_SYSCLK_DIV_1, LL_RCC_APB1_DIV_4, LL_RCC_APB2_DIV_2};

ErrorStatus System_ClockRateConfig(uint8_t cr)
{
  LL_UTILS_PLLInitTypeDef pll;
  LL_UTILS_ClkInitTypeDef clk;
  PLLParamCon_TypeDef c;

  /* Re-route clock source to HSI */
  LL_RCC_SetSysClkSource(LL_RCC_SYS_CLKSOURCE_HSI);
  while(LL_RCC_GetSysClkSource() != LL_RCC_SYS_CLKSOURCE_STATUS_HSI);
  
  /* Disable PLL */
  LL_RCC_PLL_Disable();
  
  /*Low Range Frequency -------------------------------------------------------*/
  if (cr >= LOWER_BND_LOW_CLK_RATE && cr <= UPPER_BND_LOW_CLK_RATE)
  {
    /* Disable Overdrive Mode */
    /* Disable Overdrice Switching */
    PWR->CR1 &= ~(3 << 16);
    /* Using Scale 3 Mode (Low) */
    LL_PWR_SetRegulVoltageScaling(LL_PWR_REGU_VOLTAGE_SCALE3);
    
    /* Copy map pll configuration to ClkConfig var */
    c = ClockRateScale_Low[cr - LOWER_BND_LOW_CLK_RATE];
  }
  /*Medium Range Frequency ----------------------------------------------------*/
  else if (cr == MID_CLK_RATE)
  {
    /* Disable Overdrive Mode */
    /* Disable Overdrice Switching */
    PWR->CR1 &= ~(3 << 16);
    /* Copy map pll configuration to c var */
    /* Using Scale 2 Mode (Medium) */
    LL_PWR_SetRegulVoltageScaling(LL_PWR_REGU_VOLTAGE_SCALE2);
    
    /* Copy map pll configuration to ClkConfig var */
    c = ClockRateScale_Medium;
  }
  /*High Range Frequency ------------------------------------------------------------*/
  else if (cr >= LOWER_BND_HIGH_CLK_RATE && cr <= UPPER_BND_HIGH_CLK_RATE)
  {
    /* Enable Overdrive Mode */
    LL_PWR_EnableOverDriveMode();
    while(LL_PWR_IsActiveFlag_OD() != 1);
    /* Enable Overdrice Switching */
    LL_PWR_EnableOverDriveSwitching();  
    while(LL_PWR_IsActiveFlag_ODSW() != 1);
    /* Using Scale 1 Mode (High) */
    LL_PWR_SetRegulVoltageScaling(LL_PWR_REGU_VOLTAGE_SCALE1);
    
    /* Copy map pll configuration to c var */
    c = ClockRateScale_High[cr - LOWER_BND_HIGH_CLK_RATE];
  }
  /* Insanity case, trap in inf loop */
  else 
  {
    __NOP();
  }
 
  pll.PLLM = c.PLLM;
  pll.PLLN = c.PLLN;
  pll.PLLP = c.PLLP;
  clk.AHBCLKDivider = c.AHBDiv;
  clk.APB1CLKDivider = c.APB1Div;
  clk.APB2CLKDivider = c.APB2Div;
  
  if(c.clock_src == LL_RCC_PLLSOURCE_HSE)
  {
    return LL_PLL_ConfigSystemClock_HSE(25000000, LL_UTILS_HSEBYPASS_OFF, &pll, &clk);
  }
  else
  {
    return LL_PLL_ConfigSystemClock_HSI(&pll, &clk);
  }
}

uint8_t TaskPerf_isOnStandby() 
{
  return StandbyState;
}

ErrorStatus status;
void Task_SetTaskOpClockRate(System_TaskSupervisor* instance)
{
  if(instance->task_opf <= 216 && instance->task_opf >= 60)
  {
      /*Decreasing clock rate case set*/
      if(instance->task_opf == 179)
        instance->task_opf = 168;
      if(instance->task_opf == 167 )
        instance->task_opf = 144;
      /*Increasing clock rate case set*/
      if(instance->task_opf == 145)
        instance->task_opf = 168;
      if(instance->task_opf == 169)
        instance->task_opf = 180;
  }
  else
  {
    instance->task_opf = 60;
  }
      status = System_ClockRateConfig(instance->task_opf);
}