#include "perf_config.h"
#include "stm32f7xx_ll_pwr.h"
#include "stm32f7xx_ll_rcc.h"
#include "stm32f7xx_ll_bus.h"
#include "stm32f7xx_ll_utils.h"

/* Private Prototype ******************************************************************/
/* Private Variable *******************************************************************/
static PLLParamCon_TypeDef ClkConfig;
static uint8_t StandbyState = 0;

const PLLParamCon_TypeDef ClockRateScale_Low[] = { 
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 120, LL_RCC_PLLP_DIV_4},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 122, LL_RCC_PLLP_DIV_4},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 124, LL_RCC_PLLP_DIV_4},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 126, LL_RCC_PLLP_DIV_4},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 128, LL_RCC_PLLP_DIV_4},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 130, LL_RCC_PLLP_DIV_4},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 132, LL_RCC_PLLP_DIV_4},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 134, LL_RCC_PLLP_DIV_4},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 136, LL_RCC_PLLP_DIV_4},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 138, LL_RCC_PLLP_DIV_4},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 140, LL_RCC_PLLP_DIV_4},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 142, LL_RCC_PLLP_DIV_4},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 144, LL_RCC_PLLP_DIV_4},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 146, LL_RCC_PLLP_DIV_4},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 148, LL_RCC_PLLP_DIV_4},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 150, LL_RCC_PLLP_DIV_4},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 152, LL_RCC_PLLP_DIV_4},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 154, LL_RCC_PLLP_DIV_4},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 156, LL_RCC_PLLP_DIV_4},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 158, LL_RCC_PLLP_DIV_4},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 160, LL_RCC_PLLP_DIV_4},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 162, LL_RCC_PLLP_DIV_4},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 164, LL_RCC_PLLP_DIV_4},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 166, LL_RCC_PLLP_DIV_4},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 168, LL_RCC_PLLP_DIV_4},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 170, LL_RCC_PLLP_DIV_4},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 172, LL_RCC_PLLP_DIV_4},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 174, LL_RCC_PLLP_DIV_4},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 176, LL_RCC_PLLP_DIV_4},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 178, LL_RCC_PLLP_DIV_4},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 180, LL_RCC_PLLP_DIV_4},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 182, LL_RCC_PLLP_DIV_4},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 184, LL_RCC_PLLP_DIV_4},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 186, LL_RCC_PLLP_DIV_4},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 188, LL_RCC_PLLP_DIV_4},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 190, LL_RCC_PLLP_DIV_4},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 96, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 97, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 98, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 99, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 100, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 101, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 102, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 103, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 104, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 105, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 106, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 107, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 108, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 109, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 110, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 111, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 112, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 113, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 114, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 115, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 116, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 117, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 118, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 119, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 120, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 121, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 122, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 123, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 124, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 125, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 126, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 127, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 128, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 129, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 130, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 131, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 132, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 133, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 134, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 135, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 136, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 137, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 138, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 139, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 140, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 141, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 142, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 143, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 144, LL_RCC_PLLP_DIV_2}
};
const PLLParamCon_TypeDef ClockRateScale_High[] = { 
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 180, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 181, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 182, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 183, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 184, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 185, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 186, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 187, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 188, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 189, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 190, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 191, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 192, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 193, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 194, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 195, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 196, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 197, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 198, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 199, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 200, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 201, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 202, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 203, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 204, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 205, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 206, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 207, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 208, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 209, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 210, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 211, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 212, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 213, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 214, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 215, LL_RCC_PLLP_DIV_2},
{LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 216, LL_RCC_PLLP_DIV_2}
};
const PLLParamCon_TypeDef ClockRateScale_Medium = {LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_8, 168, LL_RCC_PLLP_DIV_2};

void TaskPerf_ClockRateSwitch(uint16_t target_f) 
{
  /* Re-route clock source to HSE */
  LL_RCC_SetSysClkSource(LL_RCC_SYS_CLKSOURCE_HSE);
  while(LL_RCC_GetSysClkSource() != LL_RCC_SYS_CLKSOURCE_STATUS_HSE);
  
  /* Disable PLL */
  LL_RCC_PLL_Disable();
  
  /*Low Range Frequency -------------------------------------------------------*/
  if (target_f >= LOWER_BND_LOW_CLK_RATE && target_f <= UPPER_BND_LOW_CLK_RATE)
  {
    /* Disable Overdrive Mode */
    /* Disable Overdrice Switching */
    PWR->CR1 &= ~(3 << 16);
    /* Using Scale 3 Mode (Low) */
    LL_PWR_SetRegulVoltageScaling(LL_PWR_REGU_VOLTAGE_SCALE3);
    
    /* Copy map pll configuration to ClkConfig var */
    ClkConfig = ClockRateScale_Low[target_f - LOWER_BND_LOW_CLK_RATE];
  }
  
  /*Medium Range Frequency ----------------------------------------------------*/
  else if (target_f == MID_CLK_RATE)
  {
    /* Disable Overdrive Mode */
    LL_PWR_DisableOverDriveMode();
    /* Disable Overdrice Switching */
    LL_PWR_DisableOverDriveSwitching();
    /* Copy map pll configuration to ClkConfig var */
    /* Using Scale 2 Mode (Medium) */
    LL_PWR_SetRegulVoltageScaling(LL_PWR_REGU_VOLTAGE_SCALE2);
    ClkConfig = ClockRateScale_Medium;
  }
  
  /*High Range Frequency ------------------------------------------------------------*/
  else if (target_f >= LOWER_BND_HIGH_CLK_RATE && target_f <= UPPER_BND_HIGH_CLK_RATE)
  {
    /* Enable Overdrive Mode */
    LL_PWR_EnableOverDriveMode();
    while(LL_PWR_IsActiveFlag_OD() != 1);
    /* Enable Overdrice Switching */
    LL_PWR_EnableOverDriveSwitching();  
    while(LL_PWR_IsActiveFlag_ODSW() != 1);
    /* Using Scale 1 Mode (High) */
    LL_PWR_SetRegulVoltageScaling(LL_PWR_REGU_VOLTAGE_SCALE1);
    
    /* Copy map pll configuration to ClkConfig var */
    ClkConfig = ClockRateScale_High[target_f - LOWER_BND_HIGH_CLK_RATE];
  }
  
  /* Insanity case, trap in inf loop */
  else 
  {
    /*Standby at 8MHz*/
    if(target_f == 8) 
    {
      StandbyState = 1;
      PWR->CR1 &= ~(3 << 16);
      
      SysTick_Config((target_f * 1000000) / 1000);
      LL_SetSystemCoreClock(target_f * 1000000);
      
      return;
    }
    /*Anormaly clock rate*/
    else 
    {
      while(1);
    }
  }
  
  StandbyState = 0;
  /* Main PLL configuration and activation */
  LL_RCC_PLL_Enable();
  while(LL_RCC_PLL_IsReady() != 1);
  
  LL_RCC_PLL_ConfigDomain_SYS(ClkConfig.clock_src, 
                              ClkConfig.pll_m, 
                              ClkConfig.pll_n, 
                              ClkConfig.pll_p);

  /* Sysclk activation on the main PLL */
  LL_RCC_SetSysClkSource(LL_RCC_SYS_CLKSOURCE_PLL);
  while(LL_RCC_GetSysClkSource() != LL_RCC_SYS_CLKSOURCE_STATUS_PLL) ;

  /* Update SystemCoreClock*/
  SysTick_Config((target_f * 1000000) / 1000);
  LL_SetSystemCoreClock(target_f * 1000000);
}

uint8_t TaskPerf_isOnStandby() 
{
  return StandbyState;
}